### ISSUE TITLE
 gradlew.bat shadowjar

### ISSUE THREAD

**Issue by ASKemp** [softwareCobbler/luceedebug#36]
Getting error

Exception in thread "main" javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
...on executing gradlew.bat shadowjar

**Comment by softwareCobbler** [comment]
The following may be helpful:
- [related Gradle forum post](https://discuss.gradle.org/t/download-wrapper-fails-with-sslhandshakeexception-stacktrace/32719/5)
- [related Stackoverflow post](https://stackoverflow.com/questions/60720241/gradle-build-fails-due-to-sun-security-validator-validatorexception-despite-inst)

Not sure if there's anything we can do to improve this part of the experience from our end, it looks like an issue with the build machine's Gradle configuration. If you find a solution, please let us know what it was, and if it turns out there's something in the Gradle configuration we can change to make it "just work" in more cases, we'll do that.

**Comment by ASKemp** [comment]
Thanks. Installed Gradle manually and better luck this time but still got...

> Task :luceedebug:makeMockCfSourceFile
java.lang.UnsupportedClassVersionError: luceedebug/test/MakeMockCfFile has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)ing toolchain adoptopenjdk-11-x64-windows.zip > adoptopenjdk-11-x64-windows.zip >ndencies of :luceedebu
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)topenjdk-11-x64-windows.ziof :luceedebug:runtimeClasspath > Provisioning toolchain adop
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467) Provisioning toolchain adoptopenjdk-11-x64-windows.zip > adoptopenjdk-11-solve dependencies of :l
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)64-windows.zip > adopto
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" NG [4m 10s]
> Task :luceedebug:makeMockCfSourceFile FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':luceedebug:makeMockCfSourceFile'.
> Process 'command 'C:\Program Files\Java\jdk1.8.0_121\bin\java.exe'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4m 27s
2 actionable tasks: 2 executed

Any ideas?
