### ISSUE TITLE
java.lang.IllegalArgumentException: character to be escaped is missing  - when running latest build

### ISSUE THREAD

**Issue by anderslars** [softwareCobbler/luceedebug#40]
I had a working version from a build I made on 3/5/2023 - Windows , commandbox
no longer runs with code from master branch last updated 4/25/2023. Am able to roll back to the 3/5 version and it works (although that has some limitations - see end)

`[ERROR] Apr 29, 2023 7:04:48 AM luceedebug_shadow.org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
SEVERE: Internal error: java.lang.reflect.InvocationTargetException
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at luceedebug_shadow.org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:67)
        at luceedebug_shadow.org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
        at luceedebug_shadow.org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
        at luceedebug_shadow.org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
        at luceedebug_shadow.org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
        at luceedebug_shadow.org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
        at luceedebug_shadow.org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at luceedebug_shadow.org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
        ... 11 more
Caused by: java.lang.IllegalArgumentException: character to be escaped is missing
        at java.base/java.util.regex.Matcher.appendExpandedReplacement(Matcher.java:1020)
        at java.base/java.util.regex.Matcher.appendReplacement(Matcher.java:998)
        at java.base/java.util.regex.Matcher.replaceAll(Matcher.java:1182)
        at java.base/java.lang.String.replaceAll(String.java:2126)
        at luceedebug.DapServer.applyPathTransformsIdeToCf(DapServer.java:65)
        at luceedebug.DapServer.setBreakpoints(DapServer.java:366)
        ... 16 more
`

my config in server.json is
config - 
`    "jvm":{
        "args":[
            "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=localhost:9999",
            "-javaagent:c:\\source\\luceedebug\\luceedebug.jar=jdwpHost=localhost,jdwpPort=9999,debugHost=localhost,debugPort=10000,jarPath=c:\\source\\luceedebug\\luceedebug.jar"
        ],
        "javaVersion":"openjdk11_jdk"
    }`

for me - the version from 3/5 - I cannot use the dump commands, 
```
[ERROR] Apr 29, 2023 7:14:56 AM luceedebug_shadow.org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint request
WARNING: Unsupported request method: dumpAsJSON
```
watches kick out an exception too on the 3/5 version - but I am not going to confuse this issue with all the problems with an older version.. Suffice to say, I am keen to get the latest working version to see if I can get more of the features working.

**Comment by softwareCobbler** [comment]
Thanks for the stack trace, I think it points right at the problem, basically not escaping `\` into `\\` in `String.replaceAll`. Should be fixed in most recent build, but let us know if otherwise.

**Comment by anderslars** [comment]
Rocking. thanks so much!!! Plus all the dump functions debug console and watches - all working. Fantastic
