### ISSUE TITLE
fallbackResponseError -  java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by zspitzer** [softwareCobbler/luceedebug#50]
Similar to this issue, connecting to a Docker container runing Ubuntu, Preside / Undertow, MacOS host, using agent/2.0.10

https://github.com/softwareCobbler/luceedebug/issues/40

```
2024-06-05 14:01:52 Jun 05, 2024 1:01:52 PM luceedebug_shadow.org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
2024-06-05 14:01:52 SEVERE: Internal error: java.lang.reflect.InvocationTargetException
2024-06-05 14:01:52 java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
2024-06-05 14:01:52     at luceedebug_shadow.org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:67)
2024-06-05 14:01:52     at luceedebug_shadow.org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
2024-06-05 14:01:52     at luceedebug_shadow.org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
2024-06-05 14:01:52     at luceedebug_shadow.org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
2024-06-05 14:01:52     at luceedebug_shadow.org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
2024-06-05 14:01:52     at luceedebug_shadow.org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
2024-06-05 14:01:52     at luceedebug_shadow.org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
2024-06-05 14:01:52     at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
2024-06-05 14:01:52     at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2024-06-05 14:01:52     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2024-06-05 14:01:52     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2024-06-05 14:01:52     at java.base/java.lang.Thread.run(Thread.java:829)
2024-06-05 14:01:52 Caused by: java.lang.reflect.InvocationTargetException
2024-06-05 14:01:52     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2024-06-05 14:01:52     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2024-06-05 14:01:52     at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2024-06-05 14:01:52     at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2024-06-05 14:01:52     at luceedebug_shadow.org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
2024-06-05 14:01:52     ... 11 more
2024-06-05 14:01:52 Caused by: java.lang.UnsupportedOperationException
2024-06-05 14:01:52     at luceedebug_shadow.org.eclipse.lsp4j.debug.services.IDebugProtocolServer.source(IDebugProtocolServer.java:549)
2024-06-05 14:01:52     ... 16 more
2024-06-05 14:01:52 
```

**Comment by zspitzer** [comment]
https://github.com/eclipse-lsp4j/lsp4j/blob/main/org.eclipse.lsp4j.jsonrpc/src/main/java/org/eclipse/lsp4j/jsonrpc/services/GenericEndpoint.java#L67

**Comment by zspitzer** [comment]
@softwareCobbler looks like there's been some updates to lsp4j, latest version is 0.23.1 but there are some breaking changes https://github.com/eclipse-lsp4j/lsp4j/blob/main/CHANGELOG.md

https://github.com/zspitzer/luceedebug/actions/runs/9384040059/job/25838983670#step:6:44

**Comment by softwareCobbler** [comment]
Thanks, very minor breakage in the lsp4j update, I've patched them up in a recent commit.

Does it say which operation it was failing on? I don't see it in the stack trace. I thought we gracefully handled "unsupported" ops (well, I thought lsp4j just silently discarded ones we didn't register handlers for and/or didn't mark supported in the initial handshake), but I guess not. 

Curious if you were connecting with vscode and what version, or maybe some other IDE with DAP capabilities?

**Comment by zspitzer** [comment]
Using the latest version of VSCode, the May 2024 update, the error occurs after run start debugging, after which trying to set a break point simply won't set, it adds a listing to the breakpoints, but won't enable

I just tried the latest artifact from the github actions here, https://github.com/softwareCobbler/luceedebug/actions/runs/9391885099

slightly different stack trace, but no more clues

```
2024-06-06 10:43:11 Jun 06, 2024 9:43:11 AM luceedebug_shadow.org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
2024-06-06 10:43:11 SEVERE: Internal error: null
2024-06-06 10:43:11 java.lang.UnsupportedOperationException
2024-06-06 10:43:11     at luceedebug_shadow.org.eclipse.lsp4j.debug.services.IDebugProtocolServer.source(IDebugProtocolServer.java:549)
2024-06-06 10:43:11     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2024-06-06 10:43:11     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2024-06-06 10:43:11     at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2024-06-06 10:43:11     at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2024-06-06 10:43:11     at luceedebug_shadow.org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$recursiveFindRpcMethods$0(GenericEndpoint.java:65)
2024-06-06 10:43:11     at luceedebug_shadow.org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:128)
2024-06-06 10:43:11     at luceedebug_shadow.org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:271)
2024-06-06 10:43:11     at luceedebug_shadow.org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:201)
2024-06-06 10:43:11     at luceedebug_shadow.org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:185)
2024-06-06 10:43:11     at luceedebug_shadow.org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:97)
2024-06-06 10:43:11     at luceedebug_shadow.org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:114)
2024-06-06 10:43:11     at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
2024-06-06 10:43:11     at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2024-06-06 10:43:11     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2024-06-06 10:43:11     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2024-06-06 10:43:11     at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by softwareCobbler** [comment]
I think I see that your IDE is making a ["source"](https://microsoft.github.io/debug-adapter-protocol/specification#Requests_Source) request, where that is unimplemented and defaults to throwing UnsupportedOperationException. I've implemented it to return an error instead of throwing an exception, maybe that solves it?

**Comment by zspitzer** [comment]
So, we are making progress, it no longer throws an exception!

but I can't set breakpoints, they are listed as unbound when I list the class and breakpoint info

**Comment by softwareCobbler** [comment]
Those request headers look like a browser is trying to connect to the debugger; I can reproduce that particular error if I try to hit `localhost:<debugger-port>` from Chrome. You might have configured the debugger port to accidentally overlap with ports your app wants to use. Only a DAP client (i.e. vscode) should connect to the debugger port.

fwiw, "autoAttachChildProcesses" is not a recognized option and will have no effect. When editing a launch.json file, vscode should issue a warning on that property because it is not not part of the declared json schema for a "cfml" debug configuration.

**Comment by zspitzer** [comment]
Ok let's not worry about that error, not being able to set breakpoints is the issue, I did open the 10000 port at one point in my browser 

My config is correct, as I can dump out the json config (right?) any tips on raising log levels or other debugging approaches?

**Comment by softwareCobbler** [comment]
On the "debug class and breakpoint info", are the files listed as files Lucee knows about? Breakpoints can't be bound on files that haven't been turned into classfiles (but unbound breakpoints will be bound during classloading, i.e. once you hit page.cfm then breakpoints in that file and any files it loads should start binding). An additional constraint is that breakpoints cannot be set on the non-code textblock portions of .cfm files, since there's no code to stop on.

**Comment by zspitzer** [comment]
yeah, all the files listed and paths look 100%, I even see some lucee context files, so that indicates it's coming from Lucee, right? 

But the break points are listed as (unbound) both for server and client

**Comment by softwareCobbler** [comment]
Can you paste the full output of the "debug class and breakpoint info"?

Barring any oddities there, I'll need some kind of self contained docker repro case or something to debug this.

**Comment by softwareCobbler** [comment]
I think your path transform should be:
`idePrefix='/Users/zac/work/pixl8/clients/project/website', serverPrefix='/var/www'`

Because:
`/Users/zac/work/pixl8/clients/project/website/application/views/page-types/submission_event_listing/_popularFilters`
becomes, by the current transform {idePrefix='/Users/zac/work/pixl8/clients/project', serverPrefix='/var/www'}:
`/var/www/website/application/views/page-types/submission_event_listing/_popularFilters.cfm`

but Lucee only knows about:
`/var/www/application/views/page-types/submission_event_listing/_popularFilters.cfm`

If transform was PrefixPathTransform{idePrefix='/Users/zac/work/pixl8/clients/project/website', serverPrefix='/var/www'},
then
`/Users/zac/work/pixl8/clients/project/website/application/views/page-types/submission_event_listing/_popularFilters.cfm`
becomes
`/var/www/application/views/page-types/submission_event_listing/_popularFilters.cfm`

which matches a file Lucee knows about.

**Comment by zspitzer** [comment]
Boom and doh, thanks for all your help and patience with me on this!

Is it possible maybe to add a sanity check for silly mistakes made like that?

Also you able to publish that new release?

**Comment by softwareCobbler** [comment]
Not sure what we could do for "typos" like that, maybe some kind of Levenshtein distance thing, and surface it near the unbound lines ... like "this breakpoint is unbound but maybe you meant <some path we do know about>".

**Comment by jamiejackson** [comment]
It seems hard to justify, going through extra lengths to help with those mapping issues, unless one of those distance algorithms is straightforward to implement.

One easy-ish thing that might help:

Near the top of the debug report, it could list directories for the `serverPrefix` and `idePrefix` pairs and say something like, "if you're having trouble mapping or resolving breakpoints, compare these directory listings to make sure their contents correspond as intended."

**Comment by zspitzer** [comment]
let's close this ticket as the core issue has been resolved
